name: build_and_test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [
          {"python-version": "3.11", "pinned": true},
          {"python-version": "3.12", "pinned": true},
          {"python-version": "3.13", "pinned": true},
          {"python-version": "3.13", "pinned": false},
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything for the git tag tests.
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          python-version: ${{ matrix.variant.python-version }}
          enable-cache: true

      # Testing against the lockfile checks the PR against a known-good build.
      # One unpinned variant gives early warning of problems with the latest
      # releases of our dependencies.
      - name: Upgrade all dependencies in lockfile
        run: uv lock --upgrade
        if: matrix.variant.pinned == false

      - name: Build and install
        run: uv sync --locked

      - name: List installed packages
        run: uv tree

      - name: Run tests
        run: |
          uv run --locked pytest -r a -v --cov=tests --cov=lsst_versions --cov-report=xml --cov-report=term

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  pypi:

    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          enable-cache: true

      - name: Build and create distribution
        run: uv build

      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOADS }}
