name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the package to build.
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Build the package so that all dependencies are installed.
        run: pip install -v -e ".[dev,typing]"

      - name: Run mypy
        run: mypy python
